### ISSUE TITLE
Entries field references not beeing saved

### ISSUE THREAD

**Issue by rocknrolaf** [verbb/smith#11]
**Description**
If a matrix block type includes an entries field the reference to this entry is not saved and a validation error occurs.

**Steps to reproduce**
1. Create a matrix block with an entries field
2. Relate an entry within this entries field in the matrix block an save the entry
3. Copy this matrix block
4. Paste the matrix block into another entry with the same matrix field
5. Save the entry

**Additional info**
- Plugin version: 1.1.7 (just updated to the new version)
- Craft version: 3.5.7
- Multi-site: Yes

**Additional context**
I use this workaround which seem to work for the moment (basically it moves the fields array from the __BLOCK_... to the parameter which includes the "type" and the "enabled" attribute already. e.g. "new1") :
```
            if (Craft::$app->request->getIsPost() && Craft::$app->request->getBodyParam('action') === 'entries/save-entry') {
                $params = Craft::$app->request->getBodyParams();
                if (!empty($params['fields']['embeds']['blocks'])) {
                    $keys = array_keys($params['fields']['embeds']['blocks']);
                    $ctr = 0;
                    foreach ($params['fields']['embeds']['blocks'] as $name => $block) {
                        if (preg_match('/^__BLOCK/', $name)) {
                            $keyName = $keys[$ctr - 1];
                            $params['fields']['embeds']['blocks'][$keyName]['fields'] = $block['fields'];
                            unset($params['fields']['embeds']['blocks'][$name]);
                        }
                        $ctr++;
                    }
                    Craft::$app->request->setBodyParams($params);
                }
            }
```

**Comment by engram-design** [comment]
Should be fixed in [1.1.8](https://github.com/verbb/smith/releases/tag/1.1.8)
