### ISSUE TITLE
After copying and pasting matrix block(s) from one locale/site to another all copied fields are empty

### ISSUE THREAD

**Issue by bencresty** [verbb/smith#12]
**Description**
When copying and pasting a matrix block or multiple matrix blocks from one locale/site to another at first everything looks like a great copy; you see all blocks pasted in the other site/locale and all fields seem to have the same values. Until you save the entry and re-open the entry on that locale again; then all copied blocks are still there in the destination locale/site, but all data is gone as all fields are empty.

**Steps to reproduce**
1. Select a matrix block (or multiple blocks) to copy from locale/site A and use Copy from the menu on the/one of these blocks
2. Switch the site selector over to local/site B
3. Use Paste from one of the blocks to paste the block(s) in the other locale/site: Everything looks okay, we see the copied block(s) and all its data seems to be the same as the original
4. Click the entry Save button (the interface returns to the entry list view)
5. Open the entry again and switch to the destination locale/site where you pasted the block(s)
6. Now the copied blocks are still there, but all data is gone, all fields are empty

**Additional info**
- Plugin version: 1.1.7 (but 1.1.6 also had this issue)
- Craft version: 3.4.30 (also tested in 3.5.7: has the same issue)
- Multi-site: Yes

**Comment by engram-design** [comment]
Should be fixed in [1.1.8](https://github.com/verbb/smith/releases/tag/1.1.8)

**Comment by bencresty** [comment]
@engram-design thanks for the quick action. Looks like it's working now!
