### ISSUE TITLE
Smith doesn't work on 3.7.31 anymore

### ISSUE THREAD

**Issue by dgsiegel** [verbb/smith#20]
**Description**

With the newest Craft version 3.7.31, Smith doesn't seem to add any Copy, Paste and Clone functionality anymore.

**Steps to reproduce**
1. Update Craft to the latest version
2. Install Smith

**Additional info**
- Plugin version: 1.1.14
- Craft version: 3.7.31
- Multi-site: Yes

**Additional context**
Can't see any errors or warning in either the Craft log nor the developer console.

**Comment by engram-design** [comment]
Looks to be due to Craft 3.7.31 changes related to accessibility (https://github.com/craftcms/cms/commits/develop/src/web/assets/matrix/src/MatrixInput.js)

Fixed in [1.2.0](https://github.com/verbb/smith/releases/tag/1.2.0)
