### ISSUE TITLE
JS error thrown when viewing revisions

### ISSUE THREAD

**Issue by mmikkel** [verbb/smith#22]
**Description**

Smith throws a JS exception when viewing entry revisions:

![CleanShot 2022-03-22 at 09 17 23](https://user-images.githubusercontent.com/298510/159437040-6f2504c2-8f06-464f-9a46-bba294540901.png)

**Steps to reproduce**
1. Add a Matrix field to an entry, create some blocks, and save the entry a few times
2. Click the revision dropdown and select a previous revision

**Additional info**
- Plugin version: 1.2.0 and 2.0.0-beta.1
- Craft version: 3.7.37 and 4.0.0-beta.2
- Multi-site: No

**Additional context**

**Comment by engram-design** [comment]
Should be fixed in [1.2.1](https://github.com/verbb/smith/releases/tag/1.2.1)
