### ISSUE TITLE
Redactor fields inside cloned matrix block's aren't being initialized

### ISSUE THREAD

**Issue by MoritzLost** [verbb/smith#24]
**Description**

After cloning a matrix block with a Redactor field, the Redactor field is not being initialized properly. Here's a screencast showing the issue:

https://user-images.githubusercontent.com/10146880/171409961-ea674b7e-6ad3-429d-92b3-c3f9c5589f2b.mov

I'm not seeing any errors in the console and no server errors in the network tab. Not sure if this is an issue with this plugin or the Redactor plugin? In any case, the Redactor field works fine inside matrix blocks that are created normally, so it's probably related to the way Smith clones matrix blocks.

Copying and pasting a block results in the same issue. After reloading the page, the cloned block works normally again.

**Steps to reproduce**

1. Create a matrix block with a Redactor field inside.
2. Clone the matrix block.

**Additional info**

- Plugin version: 2.0.0-beta.1
- Craft version: 4.0.3
- Multi-site: No

**Comment by engram-design** [comment]
Should be fixed in [2.0.0](https://github.com/verbb/smith/releases/tag/2.0.0)
