### ISSUE TITLE
Button box

### ISSUE THREAD

**Issue by wmdhosting** [verbb/smith#30]
### What are you trying to do?

Button box type field >>> selected option not copied ..  allways  first option is selected in new copied block 

![Snag_36339d97](https://github.com/verbb/smith/assets/76176291/af3c80af-81e4-48cf-826f-eefb45021ecf)
![Snag_36396331](https://github.com/verbb/smith/assets/76176291/fd00236b-8c31-418e-8352-f040a73cf5d3)

### What's your proposed solution?

If posiblle copy allready selected option  from orginal block

**Comment by engram-design** [comment]
This is likely very related to https://github.com/verbb/buttonbox/issues/51#issuecomment-1432465625 and is really just to do with Button Box being implemented not quite correctly, so will be a bug with that plugin.

**Comment by wmdhosting** [comment]
this works now.   just info.. in Craft 5
