### ISSUE TITLE
Paste blocks not working in edit screen of node in Navigation Plugin

### ISSUE THREAD

**Issue by jripmeester** [verbb/smith#37]
### Describe the bug

We are using matrix blocks in the custom field layout of the navigation plugin. Now a client wants to copy/paste some of these blocks between nodes but no blocks are pasted in this edit-in-edit screen.

### Steps to reproduce

1. Install smith and navigation plugin 
2. Add matrix field to custom field layout
3. add node to navigation and and add matrix blocks to this node in the edit section
4. after saving return to edit screen en copy some matrix blocks
5. Add new node
6. Edit node and paste matrix blocks. 
7. Nothing is happening.

### Craft CMS version

4.8.0

### Plugin version

2.0.0

### Multi-site?

Yes

### Additional context

Navigation version 2.0.25

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/smith:"dev-craft-4 as 2.0.0"`.

**Comment by engram-design** [comment]
Fixed in [2.0.1](https://github.com/verbb/smith/releases/tag/2.0.1)
