### ISSUE TITLE
Copy/Paste matrix block clears content on save

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/smith#4]
### Description
Copy/Pasting a matrix block from one entry to another seems to work at first, the content is filled in in the matrix field in the new entry, but upon saving that entry, errors are triggered as the content from the matrix block is suddenly erased.

### Steps to reproduce

1. Copy matrix block from one entry
2. Paste into another entry
3. Save that entry

### Additional info

- Plugin version: 1.1.0
- Craft version: 3.4.5

**Comment by engram-design** [comment]
Fixed in [1.1.1](https://github.com/verbb/smith/releases/tag/1.1.1)
