### ISSUE TITLE
When copying and pasting a content block, a clone is also placed on the original page

### ISSUE THREAD

**Issue by belkin** [verbb/smith#43]
### Describe the bug

When copying and pasting a content block, a clone is also placed on the original page.

### Steps to reproduce

1. Copy content block on Entry A
2. Paste content block on Entry B
3. Go back to Entry A: at the bottom, the copied content block is cloned

### Craft CMS version

5.2.4.1

### Plugin version

dev-craft-5 as 3.0.0

### Multi-site?

Yes

**Comment by engram-design** [comment]
Should be fixed in [3.1.0](https://github.com/verbb/smith/releases/tag/3.1.0)
