### ISSUE TITLE
Not working with nested matrix (matrix inside Neo)

### ISSUE THREAD

**Issue by elodiegrondin** [verbb/smith#5]
### Description
First, I want to thank you for this great useful plugin.
I'm using it for a huge multisite that share some content but unfortunately this is not working in my case. I'm guessing this is caused by nested matrix.
So I have a Neo matrix field type that contain a native matrix field.

I can copy/paste/clone the first level neo matrix but the buttons are missing in the native matrix block at the second level.

Is it possible to implement this easily or it's tricky ?

**Comment by engram-design** [comment]
I'll have to look into Neo support, as I've not tested it out with nesting on that front. Will see how tricky it might be!

**Comment by engram-design** [comment]
Should be working in [1.1.4](https://github.com/verbb/smith/releases/tag/1.1.4)
