### ISSUE TITLE
Unable to clone Matrix block inside a Super Table field

### ISSUE THREAD

**Issue by kenvunz** [verbb/smith#7]
### Description
The "Paste" option is always grey out when you have a Matrix Field inside a Super Table field

### Steps to reproduce

1. Create a Super Table field with a Matrix field inside it
2. Try to copy and paste a block of that Matrix field

### Additional info

- Plugin version: 1.1.4
- Craft version: 3.4.28.1

**Comment by engram-design** [comment]
Fixed in [1.1.5](https://github.com/verbb/smith/releases/tag/1.1.5)
