### ISSUE TITLE
Paste or dublicated Matrixfield not saving content

### ISSUE THREAD

**Issue by NickLanger1990** [verbb/smith#9]
### Description
When i copy or clone a Matrixfield inside a Neo-block everthing looks fine. After saving the element the the copied Matrixfield is still there but the content is missing.

### Steps to reproduce

1. Create a Neo Field 
2. Create a Neo Block
3. Create a Matrixfield with 4 textinputs 
4. Add the Matrixfield to the Neo Block
5. Fill the Matrixfield with content and copy or dublicate that Matrixfield and safe

### Additional info

- Plugin version: 1.1.5
- Craft version: 3.4.30

**Comment by engram-design** [comment]
Fixed in [1.1.6](https://github.com/verbb/smith/releases/tag/1.1.6)
